alias: Cold Dip Heating Automation
description: Winter Automation to Manage Cold Dip Heat Mats
triggers:
  - entity_id:
      - binary_sensor.cold_dip_threshold
    id: Cold_Dip_Below_SetPoint
    trigger: state
    to: "on"
  - entity_id: switch.cold_dip_heater
    to: "on"
    id: Cold_Dip_Mats_Manual_On
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.cold_dip_timer
    id: Cold_Dip_Timer_Finished
    trigger: event
  - entity_id: switch.cold_dip_heater
    to: "off"
    id: Cold_Dip_Mats_Manual_Off
    trigger: state
  - trigger: time
    at: "00:00:00"
    id: Counter_Reset
conditions:
  - condition: template
    value_template: "{{ now().month in [11, 12, 1, 2, 3, 4] }}"
actions:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: Cold_Dip_Below_SetPoint
              - condition: state
                entity_id: input_boolean.cold_dip_lock
                state: "off"
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.cold_dip_lock
          - if:
              - condition: state
                entity_id: timer.cold_dip_cleaning
                state: active
            then:
              - action: timer.cancel
                target:
                  entity_id: timer.cold_dip_cleaning
          - condition: state
            entity_id: timer.cold_dip_timer
            state: idle
          - target:
              entity_id: switch.cold_dip_heater
            action: switch.turn_on
          - target:
              entity_id: switch.cold_dip_pump
            action: switch.turn_on
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: weather.local_forecast
                    attribute: temperature
                    below: -20
                sequence:
                  - target:
                      entity_id:
                        - timer.cold_dip_timer
                        - timer.cold_dip_cleaning
                    data:
                      duration: "04:00:00"
                    action: timer.start
              - conditions:
                  - condition: numeric_state
                    entity_id: weather.local_forecast
                    attribute: temperature
                    below: -10
                sequence:
                  - target:
                      entity_id:
                        - timer.cold_dip_timer
                        - timer.cold_dip_cleaning
                    data:
                      duration: "03:00:00"
                    action: timer.start
            default:
              - target:
                  entity_id:
                    - timer.cold_dip_timer
                    - timer.cold_dip_cleaning
                data:
                  duration: "02:00:00"
                action: timer.start
        alias: Cold_Dip_Below_SetPoint
      - conditions:
          - condition: trigger
            id: Cold_Dip_Mats_Manual_On
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.cold_dip_lock
          - target:
              entity_id: switch.cold_dip_pump
            action: switch.turn_on
          - if:
              - condition: state
                entity_id: timer.cold_dip_cleaning
                state: active
            then:
              - action: timer.cancel
                target:
                  entity_id: timer.cold_dip_cleaning
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: weather.local_forecast
                    attribute: temperature
                    below: -20
                sequence:
                  - target:
                      entity_id:
                        - timer.cold_dip_timer
                        - timer.cold_dip_cleaning
                    data:
                      duration: "04:00:00"
                    action: timer.start
              - conditions:
                  - condition: numeric_state
                    entity_id: weather.local_forecast
                    attribute: temperature
                    below: -10
                sequence:
                  - target:
                      entity_id:
                        - timer.cold_dip_timer
                        - timer.cold_dip_cleaning
                    data:
                      duration: "03:00:00"
                    action: timer.start
            default:
              - target:
                  entity_id:
                    - timer.cold_dip_timer
                    - timer.cold_dip_cleaning
                data:
                  duration: "02:00:00"
                action: timer.start
        alias: Cold_Dip_Mats_Manual_On
      - conditions:
          - condition: trigger
            id: Cold_Dip_Timer_Finished
        sequence:
          - target:
              entity_id:
                - switch.cold_dip_heater
                - switch.cold_dip_pump
            action: switch.turn_off
          - target:
              entity_id:
                - timer.cold_dip_timer
                - timer.cold_dip_cleaning
            action: timer.finish
          - action: counter.increment
            target:
              entity_id: counter.cold_dip_runtime
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.cold_dip_lock
        alias: Cold_Dip_Timer_Finished
      - conditions:
          - condition: trigger
            id: Cold_Dip_Mats_Manual_Off
        sequence:
          - target:
              entity_id:
                - switch.cold_dip_pump
                - switch.cold_dip_heater
            action: switch.turn_off
          - target:
              entity_id:
                - timer.cold_dip_timer
                - timer.cold_dip_cleaning
            action: timer.finish
          - action: counter.increment
            target:
              entity_id: counter.cold_dip_runtime
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.cold_dip_lock
        alias: Cold_Dip_Mats_Manual_Off
      - conditions:
          - condition: trigger
            id: Counter_Reset
        sequence:
          - action: counter.reset
            target:
              entity_id: counter.cold_dip_runtime
        alias: Counter_Reset
mode: restart
